//
//  HTMLEntityConverter.swift
//  TesSoMe
//
//  Created by Yuki Mizuno on 2014/09/17.
//  Copyright (c) 2014年 Yuki Mizuno. All rights reserved.
//

import UIKit

class HTMLEntityConverter: NSObject {
	class func unescape(source: String) -> String {
		var message = NSString(string: source)
		
		var htmlEntityRange = message.rangeOfString("&#[0-9]{1,4};", options: .RegularExpressionSearch)
		while htmlEntityRange.length != 0 {
			var value = message.stringByReplacingOccurrencesOfString(".*&#([0-9]{1,4});.*", withString: "$1", options: .RegularExpressionSearch, range: message.rangeOfString(".*", options: .RegularExpressionSearch)).toInt()!
			var newchar = NSString(format: "%c", value)
			
			
			message = message.stringByReplacingCharactersInRange(htmlEntityRange, withString: newchar)
			
			htmlEntityRange = message.rangeOfString("&#[0-9]{1,4};", options: .RegularExpressionSearch)
		}
		

		let result = message
		.stringByReplacingOccurrencesOfString("&quot;", withString: "\"")
		.stringByReplacingOccurrencesOfString("&quot;", withString: "\"")
		.stringByReplacingOccurrencesOfString("&lt;", withString: "<")
		.stringByReplacingOccurrencesOfString("&gt;", withString: ">")
		.stringByReplacingOccurrencesOfString("&nbsp;", withString: " ")
		.stringByReplacingOccurrencesOfString("&copy;", withString: "©")
		.stringByReplacingOccurrencesOfString("&reg;", withString: "®")
		.stringByReplacingOccurrencesOfString("&trade;", withString: "™")
		.stringByReplacingOccurrencesOfString("&yen;", withString: "¥")
		.stringByReplacingOccurrencesOfString("&emsp;", withString: "")
		.stringByReplacingOccurrencesOfString("&ensp;", withString: "")
		.stringByReplacingOccurrencesOfString("&thinsp;", withString: "")
		.stringByReplacingOccurrencesOfString("&trade;", withString: "™")
		.stringByReplacingOccurrencesOfString("&yen;", withString: "¥")
		.stringByReplacingOccurrencesOfString("&cent;", withString: "¢")
		.stringByReplacingOccurrencesOfString("&pound;", withString: "£")
		.stringByReplacingOccurrencesOfString("&euro;", withString: "€")
		.stringByReplacingOccurrencesOfString("&apos;", withString: "'")
		.stringByReplacingOccurrencesOfString("&brvbar;", withString: "¦")
		.stringByReplacingOccurrencesOfString("&micro;", withString: "µ")
		.stringByReplacingOccurrencesOfString("&permil;", withString: "‰")
		.stringByReplacingOccurrencesOfString("&curren;", withString: "¤")
		.stringByReplacingOccurrencesOfString("&uarr;", withString: "↑")
		.stringByReplacingOccurrencesOfString("&rarr;", withString: "→")
		.stringByReplacingOccurrencesOfString("&darr;", withString: "↓")
		.stringByReplacingOccurrencesOfString("&larr;", withString: "←")
		.stringByReplacingOccurrencesOfString("&harr;", withString: "↔")
		.stringByReplacingOccurrencesOfString("&uArr;", withString: "⇑")
		.stringByReplacingOccurrencesOfString("&rArr;", withString: "⇒")
		.stringByReplacingOccurrencesOfString("&dArr;", withString: "⇓")
		.stringByReplacingOccurrencesOfString("&lArr;", withString: "⇐")
		.stringByReplacingOccurrencesOfString("&hArr;", withString: "⇔")
		.stringByReplacingOccurrencesOfString("&spades;", withString: "♠")
		.stringByReplacingOccurrencesOfString("&clubs;", withString: "♣")
		.stringByReplacingOccurrencesOfString("&hearts;", withString: "♥")
		.stringByReplacingOccurrencesOfString("&diams;", withString: "♦")
		.stringByReplacingOccurrencesOfString("&ordf;", withString: "ª")
		.stringByReplacingOccurrencesOfString("&ordm;", withString: "º")
		.stringByReplacingOccurrencesOfString("&sup1;", withString: "¹")
		.stringByReplacingOccurrencesOfString("&sup2;", withString: "²")
		.stringByReplacingOccurrencesOfString("&sup3;", withString: "³")
		.stringByReplacingOccurrencesOfString("&frac12;", withString: "½")
		.stringByReplacingOccurrencesOfString("&frac14;", withString: "¼")
		.stringByReplacingOccurrencesOfString("&frac34;", withString: "¾")
		.stringByReplacingOccurrencesOfString("&minus;", withString: "−")
		.stringByReplacingOccurrencesOfString("&plusmn;", withString: "±")
		.stringByReplacingOccurrencesOfString("&times;", withString: "×")
		.stringByReplacingOccurrencesOfString("&divide;", withString: "÷")
		.stringByReplacingOccurrencesOfString("&ne;", withString: "≠")
		.stringByReplacingOccurrencesOfString("&asymp;", withString: "≈")
		.stringByReplacingOccurrencesOfString("&cong;", withString: "≅")
		.stringByReplacingOccurrencesOfString("&lt;", withString: "<")
		.stringByReplacingOccurrencesOfString("&gt;", withString: ">")
		.stringByReplacingOccurrencesOfString("&ge;", withString: "≥")
		.stringByReplacingOccurrencesOfString("&le;", withString: "≤")
		.stringByReplacingOccurrencesOfString("&infin;", withString: "∞")
		.stringByReplacingOccurrencesOfString("&radic;", withString: "√")
		.stringByReplacingOccurrencesOfString("&fnof;", withString: "ƒ")
		.stringByReplacingOccurrencesOfString("&prop;", withString: "∝")
		.stringByReplacingOccurrencesOfString("&prime;", withString: "′")
		.stringByReplacingOccurrencesOfString("&Prime;", withString: "″")
		.stringByReplacingOccurrencesOfString("&int;", withString: "∫")
		.stringByReplacingOccurrencesOfString("&part;", withString: "∂")
		.stringByReplacingOccurrencesOfString("&nabla;", withString: "∇")
		.stringByReplacingOccurrencesOfString("&sum;", withString: "∑")
		.stringByReplacingOccurrencesOfString("&prod;", withString: "∏")
		.stringByReplacingOccurrencesOfString("&image;", withString: "ℑ")
		.stringByReplacingOccurrencesOfString("&real;", withString: "ℜ")
		.stringByReplacingOccurrencesOfString("&weierp;", withString: "℘")
		.stringByReplacingOccurrencesOfString("&sim;", withString: "∼")
		.stringByReplacingOccurrencesOfString("&there4;", withString: "∴")
		.stringByReplacingOccurrencesOfString("&piv;", withString: "ϖ")
		.stringByReplacingOccurrencesOfString("&ang;", withString: "∠")
		.stringByReplacingOccurrencesOfString("&deg;", withString: "°")
		.stringByReplacingOccurrencesOfString("&perp;", withString: "⊥")
		.stringByReplacingOccurrencesOfString("&equiv;", withString: "≡")
		.stringByReplacingOccurrencesOfString("&not;", withString: "¬")
		.stringByReplacingOccurrencesOfString("&forall;", withString: "∀")
		.stringByReplacingOccurrencesOfString("&exist;", withString: "∃")
		.stringByReplacingOccurrencesOfString("&and;", withString: "∧")
		.stringByReplacingOccurrencesOfString("&or;", withString: "∨")
		.stringByReplacingOccurrencesOfString("&empty;", withString: "∅")
		.stringByReplacingOccurrencesOfString("&cap;", withString: "∩")
		.stringByReplacingOccurrencesOfString("&cup;", withString: "∪")
		.stringByReplacingOccurrencesOfString("&isin;", withString: "∈")
		.stringByReplacingOccurrencesOfString("&notin;", withString: "∉")
		.stringByReplacingOccurrencesOfString("&ni;", withString: "∋")
		.stringByReplacingOccurrencesOfString("&sub;", withString: "⊂")
		.stringByReplacingOccurrencesOfString("&sup;", withString: "⊃")
		.stringByReplacingOccurrencesOfString("&nsub;", withString: "⊄")
		.stringByReplacingOccurrencesOfString("&sube;", withString: "⊆")
		.stringByReplacingOccurrencesOfString("&supe;", withString: "⊇")
		.stringByReplacingOccurrencesOfString("&sdot;", withString: "⋅")
		.stringByReplacingOccurrencesOfString("&lowast;", withString: "∗")
		.stringByReplacingOccurrencesOfString("&oplus;", withString: "⊕")
		.stringByReplacingOccurrencesOfString("&otimes;", withString: "⊗")
		.stringByReplacingOccurrencesOfString("&lceil;", withString: "⌈")
		.stringByReplacingOccurrencesOfString("&lfloor;", withString: "⌊")
		.stringByReplacingOccurrencesOfString("&rceil;", withString: "⌉")
		.stringByReplacingOccurrencesOfString("&rfloor;", withString: "⌋")
		.stringByReplacingOccurrencesOfString("&Alpha;", withString: "Α")
		.stringByReplacingOccurrencesOfString("&alpha;", withString: "α")
		.stringByReplacingOccurrencesOfString("&Beta;", withString: "Β")
		.stringByReplacingOccurrencesOfString("&beta;", withString: "β")
		.stringByReplacingOccurrencesOfString("&Gamma;", withString: "Γ")
		.stringByReplacingOccurrencesOfString("&gamma;", withString: "γ")
		.stringByReplacingOccurrencesOfString("&Delta;", withString: "Δ")
		.stringByReplacingOccurrencesOfString("&delta;", withString: "δ")
		.stringByReplacingOccurrencesOfString("&Epsilon;", withString: "Ε")
		.stringByReplacingOccurrencesOfString("&epsilon;", withString: "ε")
		.stringByReplacingOccurrencesOfString("&Zeta;", withString: "Ζ")
		.stringByReplacingOccurrencesOfString("&zeta;", withString: "ζ")
		.stringByReplacingOccurrencesOfString("&Eta;", withString: "Η")
		.stringByReplacingOccurrencesOfString("&eta;", withString: "η")
		.stringByReplacingOccurrencesOfString("&Theta;", withString: "Θ")
		.stringByReplacingOccurrencesOfString("&theta;", withString: "θ")
		.stringByReplacingOccurrencesOfString("&Iota;", withString: "Ι")
		.stringByReplacingOccurrencesOfString("&iota;", withString: "ι")
		.stringByReplacingOccurrencesOfString("&Kappa;", withString: "Κ")
		.stringByReplacingOccurrencesOfString("&kappa;", withString: "κ")
		.stringByReplacingOccurrencesOfString("&Lambda;", withString: "Λ")
		.stringByReplacingOccurrencesOfString("&lambda;", withString: "λ")
		.stringByReplacingOccurrencesOfString("&Mu;", withString: "Μ")
		.stringByReplacingOccurrencesOfString("&mu;", withString: "μ")
		.stringByReplacingOccurrencesOfString("&Nu;", withString: "Ν")
		.stringByReplacingOccurrencesOfString("&nu;", withString: "ν")
		.stringByReplacingOccurrencesOfString("&Xi;", withString: "Ξ")
		.stringByReplacingOccurrencesOfString("&xi;", withString: "ξ")
		.stringByReplacingOccurrencesOfString("&Omicron;", withString: "Ο")
		.stringByReplacingOccurrencesOfString("&omicron;", withString: "ο")
		.stringByReplacingOccurrencesOfString("&Pi;", withString: "Π")
		.stringByReplacingOccurrencesOfString("&pi;", withString: "π")
		.stringByReplacingOccurrencesOfString("&Rho;", withString: "Ρ")
		.stringByReplacingOccurrencesOfString("&rho;", withString: "ρ")
		.stringByReplacingOccurrencesOfString("&Sigma;", withString: "Σ")
		.stringByReplacingOccurrencesOfString("&sigma;", withString: "σ")
		.stringByReplacingOccurrencesOfString("&Tau;", withString: "Τ")
		.stringByReplacingOccurrencesOfString("&tau;", withString: "τ")
		.stringByReplacingOccurrencesOfString("&Upsilon;", withString: "Υ")
		.stringByReplacingOccurrencesOfString("&upsilon;", withString: "υ")
		.stringByReplacingOccurrencesOfString("&Phi;", withString: "Φ")
		.stringByReplacingOccurrencesOfString("&phi;", withString: "φ")
		.stringByReplacingOccurrencesOfString("&Chi;", withString: "Χ")
		.stringByReplacingOccurrencesOfString("&chi;", withString: "χ")
		.stringByReplacingOccurrencesOfString("&Psi;", withString: "Ψ")
		.stringByReplacingOccurrencesOfString("&psi;", withString: "ψ")
		.stringByReplacingOccurrencesOfString("&Omega;", withString: "Ω")
		.stringByReplacingOccurrencesOfString("&omega;", withString: "ω")
		.stringByReplacingOccurrencesOfString("&acute;", withString: "´")
		.stringByReplacingOccurrencesOfString("&circ;", withString: "ˆ")
		.stringByReplacingOccurrencesOfString("&macr;", withString: "¯")
		.stringByReplacingOccurrencesOfString("&tilde;", withString: "˜")
		.stringByReplacingOccurrencesOfString("&uml;", withString: "¨")
		.stringByReplacingOccurrencesOfString("&cedil;", withString: "¸")
		.stringByReplacingOccurrencesOfString("&Aacute;", withString: "Á")
		.stringByReplacingOccurrencesOfString("&aacute;", withString: "á")
		.stringByReplacingOccurrencesOfString("&Acirc;", withString: "Â")
		.stringByReplacingOccurrencesOfString("&acirc;", withString: "â")
		.stringByReplacingOccurrencesOfString("&AElig;", withString: "Æ")
		.stringByReplacingOccurrencesOfString("&aelig;", withString: "æ")
		.stringByReplacingOccurrencesOfString("&Agrave;", withString: "À")
		.stringByReplacingOccurrencesOfString("&agrave;", withString: "à")
		.stringByReplacingOccurrencesOfString("&Aring;", withString: "Å")
		.stringByReplacingOccurrencesOfString("&aring;", withString: "å")
		.stringByReplacingOccurrencesOfString("&Atilde;", withString: "Ã")
		.stringByReplacingOccurrencesOfString("&atilde;", withString: "ã")
		.stringByReplacingOccurrencesOfString("&Auml;", withString: "Ä")
		.stringByReplacingOccurrencesOfString("&auml;", withString: "ä")
		.stringByReplacingOccurrencesOfString("&Ccedil;", withString: "Ç")
		.stringByReplacingOccurrencesOfString("&ccedil;", withString: "ç")
		.stringByReplacingOccurrencesOfString("&Eacute;", withString: "É")
		.stringByReplacingOccurrencesOfString("&eacute;", withString: "é")
		.stringByReplacingOccurrencesOfString("&Ecirc;", withString: "Ê")
		.stringByReplacingOccurrencesOfString("&ecirc;", withString: "ê")
		.stringByReplacingOccurrencesOfString("&Egrave;", withString: "È")
		.stringByReplacingOccurrencesOfString("&egrave;", withString: "è")
		.stringByReplacingOccurrencesOfString("&ETH;", withString: "Ð")
		.stringByReplacingOccurrencesOfString("&eth;", withString: "ð")
		.stringByReplacingOccurrencesOfString("&Euml;", withString: "Ë")
		.stringByReplacingOccurrencesOfString("&euml;", withString: "ë")
		.stringByReplacingOccurrencesOfString("&Iacute;", withString: "Í")
		.stringByReplacingOccurrencesOfString("&iacute;", withString: "í")
		.stringByReplacingOccurrencesOfString("&Icirc;", withString: "Î")
		.stringByReplacingOccurrencesOfString("&icirc;", withString: "î")
		.stringByReplacingOccurrencesOfString("&Igrave;", withString: "Ì")
		.stringByReplacingOccurrencesOfString("&igrave;", withString: "ì")
		.stringByReplacingOccurrencesOfString("&Iuml;", withString: "Ï")
		.stringByReplacingOccurrencesOfString("&iuml;", withString: "ï")
		.stringByReplacingOccurrencesOfString("&Ntilde;", withString: "Ñ")
		.stringByReplacingOccurrencesOfString("&ntilde;", withString: "ñ")
		.stringByReplacingOccurrencesOfString("&Oacute;", withString: "Ó")
		.stringByReplacingOccurrencesOfString("&oacute;", withString: "ó")
		.stringByReplacingOccurrencesOfString("&Ocirc;", withString: "Ô")
		.stringByReplacingOccurrencesOfString("&ocirc;", withString: "ô")
		.stringByReplacingOccurrencesOfString("&Ograve;", withString: "Ò")
		.stringByReplacingOccurrencesOfString("&ograve;", withString: "ò")
		.stringByReplacingOccurrencesOfString("&Oslash;", withString: "Ø")
		.stringByReplacingOccurrencesOfString("&oslash;", withString: "ø")
		.stringByReplacingOccurrencesOfString("&Otilde;", withString: "Õ")
		.stringByReplacingOccurrencesOfString("&otilde;", withString: "õ")
		.stringByReplacingOccurrencesOfString("&Ouml;", withString: "Ö")
		.stringByReplacingOccurrencesOfString("&ouml;", withString: "ö")
		.stringByReplacingOccurrencesOfString("&OElig;", withString: "Œ")
		.stringByReplacingOccurrencesOfString("&oelig;", withString: "œ")
		.stringByReplacingOccurrencesOfString("&szlig;", withString: "ß")
		.stringByReplacingOccurrencesOfString("&Scaron;", withString: "Š")
		.stringByReplacingOccurrencesOfString("&scaron;", withString: "š")
		.stringByReplacingOccurrencesOfString("&THORN;", withString: "Þ")
		.stringByReplacingOccurrencesOfString("&thorn;", withString: "þ")
		.stringByReplacingOccurrencesOfString("&Uacute;", withString: "Ú")
		.stringByReplacingOccurrencesOfString("&uacute;", withString: "ú")
		.stringByReplacingOccurrencesOfString("&Ucirc;", withString: "Û")
		.stringByReplacingOccurrencesOfString("&ucirc;", withString: "û")
		.stringByReplacingOccurrencesOfString("&Ugrave;", withString: "Ù")
		.stringByReplacingOccurrencesOfString("&ugrave;", withString: "ù")
		.stringByReplacingOccurrencesOfString("&Uuml;", withString: "Ü")
		.stringByReplacingOccurrencesOfString("&uuml;", withString: "ü")
		.stringByReplacingOccurrencesOfString("&Yacute;", withString: "Ý")
		.stringByReplacingOccurrencesOfString("&yacute;", withString: "ý")
		.stringByReplacingOccurrencesOfString("&Yuml;", withString: "Ÿ")
		.stringByReplacingOccurrencesOfString("&yuml;", withString: "ÿ")
		.stringByReplacingOccurrencesOfString("&amp;", withString: "&")
		
		return result
	}
}
